//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnitityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posten
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Posten()
        {
            this.Bestellung = new HashSet<Bestellung>();
        }
    
        public int ID_Posten { get; set; }
        public Nullable<int> ID_Produkt { get; set; }
        public Nullable<int> Anzahl { get; set; }
        public Nullable<decimal> Preis { get; set; }
    
        public virtual Produkt Produkt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bestellung> Bestellung { get; set; }
    }
}
